#!/bin/sh -
#
#   @(#)netstart        8.1 (Berkeley) 7/23/93

routedflags=-q
timedflags=NO
rwhod=NO

# myname is my symbolic name
# my-netmask is specified in /etc/networks
#
hostname=bsd.net
hostname $hostname

#ifconfig ace0 inet $hostname netmask my-netmask
#ifconfig  ex0 inet $hostname netmask my-netmask
#ifconfig imp0 inet $hostname
#ifconfig  le0 inet $hostname netmask my-netmask
#ifconfig  ne0 inet $hostname netmask my-netmask
#ifconfig  we0 inet $hostname netmask my-netmask

if ifconfig en0 >/dev/null 2>&1; then
    ifconfig en0 inet 10.0.2.15
    gateway=10.0.2.2
fi

# set the address for the loopback interface
ifconfig lo0 inet 127.0.0.1

# use loopback, not the wire
#route add $hostname localhost

# default route
if [ -n "$gateway" ]; then
    route add -net 0 $gateway
fi
