#	@(#)Makefile	8.5 (Berkeley) 3/31/94

SUBDIR=	badsect clri dmesg dump dumpfs dumplfs fastboot \
	fsck fsck_ffs ifconfig init mknod mount mount_cd9660 mount_fdesc \
	mount_kernfs mount_lfs mount_nfs mount_null mount_portal \
	mount_procfs mount_umap mount_union mountd newfs newlfs nfsd \
	nfsiod nologin ping quotacheck reboot restore route routed savecore \
	scsiformat shutdown slattach startslip swapon tunefs umount
#TODO: fsdb icheck ncheck
.include <bsd.subdir.mk>
