#	@(#)Makefile	8.2 (Berkeley) 4/3/94

PROG=	compress
SRCS=	compress.c
LINKS=	${BINDIR}/compress ${BINDIR}/uncompress ${BINDIR}/compress ${BINDIR}/zcat
MLINKS= compress.1 uncompress.1 compress.1 zcat.1

.include <bsd.prog.mk>
