#	@(#)Makefile	8.1 (Berkeley) 6/4/93

LIB=json
CFLAGS+=-Wall -Werror

SRCS=json_c_version.c json_object.c json_object_iterator.c \
    json_tokener.c json_util.c arraylist.c debug.c linkhash.c \
    printbuf.c random_seed.c

.include <bsd.lib.mk>
