
OBJS    = wf_connection.o \
          wf_profile.o \
          wf_data_msg.o \
          wf_eint.o \
          wf_eint_stub.o \
          wf_event.o \
          wf_event_stub.o \
          wf_gpio_stub.o \
          wf_init.o \
          wf_mgmt_msg.o \
          wf_param_msg.o \
          wf_pbkdf2.o \
          wf_pll.o \
          wf_power.o \
          wf_raw.o \
          wf_registers.o \
          wf_scan.o \
          wf_spi_stub.o \
          wf_task.o \
          wf_timer.o \
          wf_timer_stub.o \
          wf_ud_state.o

CFLAGS  = -Wall -DWF_ERROR_CHECKING

all:    $(OBJS)

clean:
	rm -f *.o
