/*
 * MRF24WG Initialization
 *
 * Functions pertaining Universal Driver and MRF24WG initialization.
 */
#include "wf_universal_driver.h"
#include "wf_global_includes.h"

extern void WF_SetTxDataConfirm(u_int8_t state);

/*
 * Initialize interrupts generated by MRF24WG module.
 */
static void Init_Interrupts()
{
    unsigned mask, mask2;

    // disable the interrupts gated by the 16-bit host int register
    mrf_write(MRF24_REG_MASK2, 0);
    mrf_write(MRF24_REG_INTR2, 0xffff);

    // disable the interrupts gated the by main 8-bit host int register
    mrf_write_byte(MRF24_REG_MASK, 0);
    mrf_write_byte(MRF24_REG_INTR, 0xff);

    // Initialize the External Interrupt for the MRF24W allowing the MRF24W to interrupt
    // the Host from this point forward.
    mrf_intr_init();
    mrf_intr_enable();

    // enable the following MRF24W interrupts in the INT1 8-bit register
    mask = INTR_FIFO0 | INTR_FIFO1 | INTR_RAW0 | INTR_RAW1 | INTR_INT2;
    mrf_write_byte(MRF24_REG_MASK, mask);
    mrf_write_byte(MRF24_REG_INTR, mask);

    // enable the following MRF24W interrupts in the INT2 16-bit register
    mask2 = INTR2_RAW2 | INTR2_RAW3 | INTR2_RAW4 | INTR2_RAW5 | INTR2_MAILBOX;
    mrf_write(MRF24_REG_MASK2, mask2);
    mrf_write(MRF24_REG_INTR2, mask2);
}

/*
 * Initialize the MRF24WG for operations.
 * Must be called before any other WiFi API calls.
 */
void WF_Init(t_deviceInfo *deviceInfo)
{
    unsigned msec, value;

    UdStateInit();          // initialize internal state machine
    ClearMgmtConfirmMsg();  // no mgmt response messages received
    UdSetInitInvalid();     // init not valid until it gets through this state machine

    /*
     * Reset the chip.
     */

    // clear the power bit to disable low power mode on the MRF24W
    mrf_write(MRF24_REG_PSPOLL, 0);

    // Set HOST_RESET bit in register to put device in reset
    mrf_write(MRF24_REG_RESET, mrf_read(MRF24_REG_RESET) | RESET_SOFT_RESET);

    // Clear HOST_RESET bit in register to take device out of reset
    mrf_write(MRF24_REG_RESET, mrf_read(MRF24_REG_RESET) & ~RESET_SOFT_RESET);

    /*
     * Wait for chip to initialize itself, up to 2 sec.
     * Usually it takes about 140 msec until all registers are ready..
     */
    for (msec=0; msec<2000; msec++) {
        value = mrf_read(MRF24_REG_WFIFO_BCNT0);
        if (value & FIFO_BCNT_MASK)
            break;
        udelay(1000);
    }

    /*
     * Finish the MRF24WG intitialization.
     */
    Init_Interrupts();                  // Initialize MRF24WG interrupts
    RawInit();                          // initialize RAW driver
    WFEnableMRF24WB0MMode();            // legacy, but still needed
    WF_DeviceInfoGet(deviceInfo);       // get MRF24WG module version numbers
    switch (deviceInfo->deviceType) {
    case WF_UNKNOWN_DEVICE:
        /* Cannot happen. */
        break;

    case WF_MRF24WB_DEVICE:
        /* MRF24WB chip not supported by this driver. */
        break;

    case WF_MRF24WG_DEVICE:
        WF_SetTxDataConfirm(WF_DISABLED); // Disable Tx Data confirms (from the MRF24W)
        WF_CPCreate();                  // create a connection profile, get its ID and store it
        WF_PsPollDisable();
        ClearPsPollReactivate();
        UdSetInitValid();               // Chip initialized successfully.
        break;
    }
}
