/*
 * DO NOT EDIT THIS FILE BY HAND!
 * It is generated by ./base/MKlib_gen.sh generated.
 *
 * This is a file of trivial functions generated from macro
 * definitions in curses.h to satisfy the XSI Curses requirement
 * that every macro also exist as a callable function.
 *
 * It will never be linked unless you call one of the entry
 * points with its normal macro definition disabled. In that
 * case, if you have no shared libraries, it will indirectly
 * pull most of the rest of the library into your link image.
 */
#define NCURSES_ATTR_T int
#include <ncurses_cfg.h>

#undef NCURSES_NOMACROS /* _this_ file uses macros */

#include <curses.priv.h>

#undef vw_scanw
#undef vwscanw

#undef vw_printw
#undef vwprintw
