/*
 * DO NOT EDIT THIS FILE BY HAND!
 * It is generated by ./base/MKlib_gen.sh implemented.
 */
#define NCURSES_ATTR_T int
#include <ncurses_cfg.h>

#undef NCURSES_NOMACROS /* _this_ file uses macros */

#include <curses.priv.h>

#undef vw_scanw
#undef vwscanw

#undef vw_printw
#undef vwprintw
int main(void)
{
 return 0;
}
